"""
Report generator for Hermes Wiki.
Generates markdown reports locally. No external uploads.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Iterable

from indexer import load_index, REPORTS_DIR, SNAPSHOTS_DIR, ensure_dirs
from scanner import scan_all
from cron_map import build_cron_map, format_cron_table
from skill_map import scan_skill_dir, format_skill_table
from trust_map import build_trust_map, format_trust_table
from server_map import collect_server_health, format_health_markdown
from load_rank import build_load_rank, format_load_table
from garbage_map import build_garbage_map, format_garbage_table
from cleanup_advisor import build_cleanup_advice, format_cleanup_report


def generate_report(include_server: bool = False) -> str:
    """Generate comprehensive markdown report."""
    lines = [
        "# Hermes Wiki Report",
        f"**Generated:** {datetime.now().isoformat()}",
        "",
        "## 1. Code Map Summary",
        "",
    ]

    code_entries = load_index("code")
    lines.append(f"- **Total files scanned:** {len(code_entries)}")
    risk_counts = {}
    for e in code_entries:
        rc = e.get("risk_class", "UNKNOWN")
        risk_counts[rc] = risk_counts.get(rc, 0) + 1
    lines.append("- **Risk distribution:**")
    for rc, count in sorted(risk_counts.items()):
        lines.append(f"  - {rc}: {count}")
    lines.append("")

    # High risk files
    high_risk = [e for e in code_entries if e.get("risk_class") in ("HIGH", "CRITICAL")]
    if high_risk:
        lines.append("### High Risk Files")
        for e in high_risk[:20]:
            lines.append(f"- {e.get('path', '?')} ({e.get('risk_class', '?')})")
        lines.append("")

    # Cron map
    lines.extend([
        "## 2. Cron Map",
        "",
    ])
    cron_entries = load_index("cron")
    broken = [e for e in cron_entries if e.get("broken")]
    lines.append(f"- **Total cron entries:** {len(cron_entries)}")
    lines.append(f"- **Broken paths:** {len(broken)}")
    if broken:
        lines.append("### Broken Cron Jobs")
        for e in broken:
            lines.append(f"- {e.get('schedule', '?')} -> {e.get('script_path', '?')}")
    lines.append("")

    # Skill map
    lines.extend([
        "## 3. Skill Map",
        "",
    ])
    skills = load_index("skills")
    missing_tests = [s for s in skills if not s.get("has_tests")]
    missing_docs = [s for s in skills if s.get("missing_docs")]
    lines.append(f"- **Total skills:** {len(skills)}")
    lines.append(f"- **Missing tests:** {len(missing_tests)}")
    lines.append(f"- **Missing docs:** {len(missing_docs)}")
    lines.append("")

    # Trust map
    lines.extend([
        "## 4. Trust Map Summary",
        "",
    ])
    trust = load_index("trust")
    high_trust = [e for e in trust if e.get("risk_class") in ("HIGH", "CRITICAL")]
    secret_trust = [e for e in trust if e.get("risk_class") == "SECRET_OR_UNKNOWN"]
    lines.append(f"- **Total files analyzed:** {len(trust)}")
    lines.append(f"- **High/Critical risk:** {len(high_trust)}")
    lines.append(f"- **Secret/Unknown:** {len(secret_trust)}")
    lines.append("")

    if include_server:
        lines.extend([
            "## 5. Server Health",
            "",
        ])
        try:
            health = collect_server_health()
            lines.append(format_health_markdown(health))
        except Exception as e:
            lines.append(f"Server health collection failed: {e}")
        lines.append("")

        lines.extend([
            "## 6. Load Ranking",
            "",
        ])
        try:
            load_entries = build_load_rank()
            lines.append(format_load_table(load_entries))
        except Exception as e:
            lines.append(f"Load ranking failed: {e}")
        lines.append("")

        lines.extend([
            "## 7. Garbage Map",
            "",
        ])
        try:
            garbage = build_garbage_map()
            lines.append(format_garbage_table(garbage))
        except Exception as e:
            lines.append(f"Garbage map failed: {e}")
        lines.append("")

        lines.extend([
            "## 8. Cleanup Advisor",
            "",
        ])
        try:
            advice = build_cleanup_advice()
            lines.append(format_cleanup_report(advice))
        except Exception as e:
            lines.append(f"Cleanup advisor failed: {e}")
        lines.append("")

    lines.extend([
        "---",
        "*Report generated by Hermes Wiki - local-only, read-only.*",
    ])

    return "\n".join(lines)


def save_report(include_server: bool = False) -> Path:
    """Generate and save report to local directory."""
    ensure_dirs()
    report = generate_report(include_server)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = REPORTS_DIR / f"report_{timestamp}.md"
    path.write_text(report, encoding="utf-8")
    print(f"Report saved to {path}")
    return path


def save_snapshot():
    """Save current index state as snapshot for diff tracking."""
    ensure_dirs()
    snapshot = {
        "timestamp": datetime.now().isoformat(),
        "code_count": len(load_index("code")),
        "cron_count": len(load_index("cron")),
        "skill_count": len(load_index("skills")),
        "trust_count": len(load_index("trust")),
    }
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = SNAPSHOTS_DIR / f"snapshot_{timestamp}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(snapshot, f, indent=2)
    print(f"Snapshot saved to {path}")
    return path
